Repository civicrm/civicrm-drupal, pull requests merged in 2019-08, with the labels that each got.

#583 (dev/drupal#79) Fail more gracefully when upgrading on PHP 5.x
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviDrupal/PhpVersionTest.php
Labels: 7.x-5.17

#584 (dev/drupal#79) Fail more gracefully when upgrading on PHP 5.x
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviDrupal/PhpVersionTest.php
Labels: 7.x-5.16

#582 providing clear indication that civicrm_engage module is deprecated.
  modules/civicrm_engage/civicrm_engage.info
Labels: 7.x-master
