Repository civicrm/civicrm-drupal, pull requests merged in 2019-11, with the labels that each got.

#586 [NFC] Update copyright date for 2020
  api.php
  civicrm.install
  civicrm.module
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_og_sync/civicrm_og_sync.module
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_civicrm_contact.eval.inc
  modules/civicrm_rules/civicrm_rules_civicrm_event.eval.inc
  modules/civicrm_rules/civicrm_rules_civicrm_participant.eval.inc
  modules/civicrm_rules/utils.inc
Labels: 6.x-master

#585 [NFC] Update copyright date for 2020
  civicrm.install
  civicrm.module
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Form/Inline/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Page/Inline/Demographics.tpl
  modules/civicrm_og_sync/civicrm_og_sync.install
  modules/civicrm_og_sync/civicrm_og_sync.module
  modules/civicrm_rules/civicrm_rules.contact-eval.inc
  modules/civicrm_rules/civicrm_rules.event-eval.inc
  modules/civicrm_rules/civicrm_rules.install
  modules/civicrm_rules/civicrm_rules.mailing-eval.inc
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.participant-eval.inc
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_action.inc
  modules/civicrm_rules/civicrm_rules_condition.inc
  modules/civicrm_rules/civicrm_rules_entity.inc
  modules/civicrm_rules/civicrm_rules_event.inc
  modules/civicrm_rules/civicrm_rules_utils.inc
  modules/civicrmtheme/civicrmtheme.install
  modules/civicrmtheme/civicrmtheme.module
Labels: 7.x-master, merge-on-pass

#588 (NFC) (dev/core#878) Simplify copyright header
  api.php
  civicrm.install
  civicrm.module
  civitest.module.sample
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_engage/templates/Engage/Report/Form/CallList.tpl
  modules/civicrm_og_sync/civicrm_og_sync.module
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_civicrm_contact.eval.inc
  modules/civicrm_rules/civicrm_rules_civicrm_event.eval.inc
  modules/civicrm_rules/civicrm_rules_civicrm_participant.eval.inc
  modules/civicrm_rules/utils.inc
Labels: 6.x-master

#587 (NFC) (dev/core#878) Simplify copyright header (D7)
  civicrm.install
  civicrm.module
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Form/Inline/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Page/Inline/Demographics.tpl
  modules/civicrm_member_roles/CHANGELOG.txt
  modules/civicrm_og_sync/civicrm_og_sync.install
  modules/civicrm_og_sync/civicrm_og_sync.module
  modules/civicrm_rules/civicrm_rules.contact-eval.inc
  modules/civicrm_rules/civicrm_rules.event-eval.inc
  modules/civicrm_rules/civicrm_rules.install
  modules/civicrm_rules/civicrm_rules.mailing-eval.inc
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.participant-eval.inc
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_action.inc
  modules/civicrm_rules/civicrm_rules_condition.inc
  modules/civicrm_rules/civicrm_rules_entity.inc
  modules/civicrm_rules/civicrm_rules_event.inc
  modules/civicrm_rules/civicrm_rules_utils.inc
  modules/civicrmtheme/civicrmtheme.install
  modules/civicrmtheme/civicrmtheme.module
Labels: 7.x-master

#590 Add participant is_test field to views
  modules/views/components/civicrm.event.inc
Labels: 7.x-master
