Repository civicrm/civicrm-drupal, pull requests merged in 2019-04, with the labels that each got.

#571 Update 7.x Drupal code to be that of the new coder style
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  tests/phpunit/CiviDrupal/HookTest.php
Labels: 7.x-5.13

#572 7.x 5.13
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  tests/phpunit/CiviDrupal/HookTest.php
Labels: 7.x-master

#575 (NFC) Get phpcs to ignore the use of eval in this file as it is required
  tests/phpunit/bootstrap.php
Labels: 7.x-5.13, merge-on-pass

#577 (NFC) Update for compliance with next phpcs standard
  civicrm.module
  modules/civicrm_contact_ref/civicrm_contact_ref.module
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_group_roles/civicrm_group_roles.module
  modules/civicrm_member_roles/civicrm_member_roles.module
  modules/civicrm_og_sync/civicrm_og_sync.module
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrmtheme/civicrmtheme.module
Labels: 7.x-5.13, merge-on-pass

#578 Issue 48: make it next_sched_contribution_date
  modules/views/components/civicrm.contribute.inc
Labels: 7.x-master

#540 Don't render an empty mailto link for empty email addresses
  modules/views/civicrm/civicrm_handler_field_email.inc
Labels: 7.x-master

#573 Enable contribution views to filter on empty Receipt and Thank You dates
  modules/views/components/civicrm.contribute.inc
Labels: 7.x-master

#567 Bump php version to match core requirements
  civicrm.info
Labels: 7.x-master

#507 CRM-20006 Standard groups relationships in views
  civicrm.info
  modules/views/civicrm.views.inc
  modules/views/civicrm/civicrm_handler_filter_group_name.inc
  modules/views/civicrm/civicrm_handler_relationship_group.inc
  modules/views/civicrm/civicrm_handler_relationship_standard_group.inc
  modules/views/civicrm/civicrm_handler_relationship_standard_group_contact.inc
  modules/views/components/civicrm.core.inc
Labels: 7.x-master
