Repository civicrm/civicrm-drupal, pull requests merged in 2020-12, with the labels that each got.

#629 Update civicrm.module links
  civicrm.module
Labels: 7.x-5.33

#630 Update doclink trouble as per Mikey's comment
  civicrm.module
Labels: 7.x-5.33, merge-on-pass

#631 7.x 5.33
  civicrm.module
Labels: 7.x-master

#624 Update docs links
  civicrm.module
Labels: 7.x-master, merge-on-pass
