Repository civicrm/civicrm-drupal, pull requests merged in 2022-03, with the labels that each got.

#653 Views - CiviGrant is now an extension
  modules/views/civicrm.views.inc
Labels: 7.x-5.47

#655 7.x 5.48
  modules/views/civicrm.views.inc
Labels: 7.x-master

#652 civicrm.drush.inc - Add 'civicrm-pipe' subcommand
  drush/civicrm.drush.inc
Labels: 7.x-master, merge-on-pass

#656 civicrm_handler_filter_pseudo_constant - Guard against old or inactive pseudoconstants
  modules/views/civicrm/civicrm_handler_filter_pseudo_constant.inc
Labels: 7.x-5.48

#658 civicrm_handler_filter_pseudo_constant - Guard against old or inactive pseudoconstants
  modules/views/civicrm/civicrm_handler_filter_pseudo_constant.inc
Labels: merge-on-pass, 7.x-5.47

#657 7.x 5.48
  modules/views/civicrm/civicrm_handler_filter_pseudo_constant.inc
Labels: 7.x-master
