Repository civicrm/civicrm-drupal, pull requests merged in 2023-09, with the labels that each got.

#670 phpunit.xml.dist - Fix compatibility with phpunit9
  phpunit.xml.dist
Labels: 7.x-5.66

#671 phpunit.xml.dist - Fix compatibility with phpunit9
  phpunit.xml.dist
Labels: 7.x-5.65

#672 7.x 5.66
  phpunit.xml.dist
Labels: 7.x-master

#669 Views notice fix. Remove duplicate call to constructor.
  modules/views/civicrm/civicrm_handler_field_pseudo_constant.inc
  modules/views/civicrm/civicrm_handler_filter_pseudo_constant.inc
Labels: 7.x-master
