Repository civicrm/civicrm-drupal, pull requests merged in 2024-09, with the labels that each got.

#685 Setup UI - Restore icons (FontAwesome 6 support)
  civicrm.setup.inc
Labels: 7.x-5.77

#684 Remove event_cart link from Drupal7 Views
  modules/views/civicrm/civicrm_handler_field_event_link.inc
Labels: merge-on-pass, 7.x-5.78

#686 Switch to less-deprecated buildOptions function
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
Labels: 7.x-5.78

#687 Merge 5.78 to master
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/views/civicrm/civicrm_handler_field_event_link.inc
Labels: 7.x-master

#688 D7 Views - Update some deprecated pseudoconstant function calls
  modules/views/civicrm/civicrm_handler_field_activity.inc
  modules/views/civicrm/civicrm_handler_field_im.inc
  modules/views/civicrm/civicrm_handler_field_location.inc
  modules/views/civicrm/civicrm_handler_field_phone.inc
  modules/views/civicrm/civicrm_handler_field_website.inc
  modules/views/civicrm/civicrm_handler_relationship_im.inc
  modules/views/civicrm/civicrm_handler_relationship_location.inc
  modules/views/civicrm/civicrm_handler_relationship_phone.inc
  modules/views/civicrm/civicrm_handler_relationship_website.inc
Labels: 7.x-master
